package gafetes;

/*
 * SplashDialog.java
 *
 * Created on 9 ottobre 2004, 11.19
 */



/**
 *
 * @author  Administrator
 */
import gafetes.util.*;

public class SplashDialog extends javax.swing.JDialog {
    
    /** Creates new form SplashDialog */
    public SplashDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        this.setSize(320,261);
        this.setSize(640,480);
        gafetes.util.Misc.centerFrame(this);
    }
    
    public void updateLoadingStatus(int status, String label)
    {
        jProgressBar1.setValue(status);
        if (label != null) jProgressBar1.setString( label);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("images/logo4.jpg")));
        jLabel1.setIconTextGap(0);
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        jProgressBar1.setOpaque(false);
        jProgressBar1.setString("Loading");
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
}
